import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Serif_Lao } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifLao = Noto_Serif_Lao({
  variable: "--font-lao",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["lao"],
});

export const metadata: Metadata = {
  title: "Hmong Fashion Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="lo">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifLao.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
